abilities = {
    "bard": [
        {
            "key": "q",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 688, "top": 1019, "width": 34, "height": 34},
            "directional": False,
        },
        {
            "key": "w",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 737, "top": 1019, "width": 34, "height": 34},
            "directional": True,
        },
        {
            "key": "e",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 781, "top": 1019, "width": 34, "height": 34},
            "directional": True,
        },
        {
            "key": "r",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 828, "top": 1019, "width": 34, "height": 34},
            "directional": False,
        },
        {
            "key": "a",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 709, "top": 1063, "width": 34, "height": 34},
            "directional": True,
        },
        {
            "key": "s",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 756, "top": 1063, "width": 34, "height": 34},
            "directional": False,
        },
        {
            "key": "d",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 803, "top": 1063, "width": 34, "height": 34},
            "directional": False,
        },
        {
            "key": "f",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 849, "top": 1063, "width": 34, "height": 34},
            "directional": False,
        },
    ],
    "holyknight": [
        {
            "key": "q",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 688, "top": 1019, "width": 34, "height": 34},
            "directional": False,
        },
        {
            "key": "w",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 737, "top": 1019, "width": 34, "height": 34},
            "directional": True,
        },
        {
            "key": "e",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 781, "top": 1019, "width": 34, "height": 34},
            "directional": True,
        },
        {
            "key": "r",
            "abilityType": "normal",
            "hold": True,
            "holdTime": 1,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 828, "top": 1019, "width": 34, "height": 34},
            "directional": False,
        },
        {
            "key": "a",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 709, "top": 1063, "width": 34, "height": 34},
            "directional": True,
        },
        {
            "key": "s",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 756, "top": 1063, "width": 34, "height": 34},
            "directional": False,
        },
        {
            "key": "d",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": True,
            "position": {"left": 803, "top": 1063, "width": 34, "height": 34},
            "directional": False,
        },
        {
            "key": "f",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 849, "top": 1063, "width": 34, "height": 34},
            "directional": False,
        },
    ],
    "demonic": [
        {
            "key": "q",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": True,
            "position": {"left": 688, "top": 1019, "width": 34, "height": 34},
            "directional": False,
        },
        {
            "key": "w",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 737, "top": 1019, "width": 34, "height": 34},
            "directional": True,
        },
        {
            "key": "e",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 781, "top": 1019, "width": 34, "height": 34},
            "directional": True,
        },
        {
            "key": "r",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 828, "top": 1019, "width": 34, "height": 34},
            "directional": False,
        },
        {
            "key": "a",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 709, "top": 1063, "width": 34, "height": 34},
            "directional": True,
        },
        {
            "key": "s",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 756, "top": 1063, "width": 34, "height": 34},
            "directional": False,
        },
        {
            "key": "d",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 803, "top": 1063, "width": 34, "height": 34},
            "directional": False,
        },
        {
            "key": "f",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 849, "top": 1063, "width": 34, "height": 34},
            "directional": False,
        },
    ],
    "slayer": [
        {
            "key": "q",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 688, "top": 1019, "width": 34, "height": 34},
            "directional": False,
        },
        {
            "key": "w",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 737, "top": 1019, "width": 34, "height": 34},
            "directional": True,
        },
        {
            "key": "e",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 781, "top": 1019, "width": 34, "height": 34},
            "directional": True,
        },
        {
            "key": "r",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 828, "top": 1019, "width": 34, "height": 34},
            "directional": False,
        },
        {
            "key": "a",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 709, "top": 1063, "width": 34, "height": 34},
            "directional": True,
        },
        {
            "key": "s",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 756, "top": 1063, "width": 34, "height": 34},
            "directional": False,
        },
        {
            "key": "d",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 803, "top": 1063, "width": 34, "height": 34},
            "directional": False,
        },
        {
            "key": "f",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 849, "top": 1063, "width": 34, "height": 34},
            "directional": False,
        },
    ],
    "sorceress": [
        {
            "key": "q",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 688, "top": 1019, "width": 34, "height": 34},
            "directional": False,
        },
        {
            "key": "w",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 737, "top": 1019, "width": 34, "height": 34},
            "directional": True,
        },
        {
            "key": "e",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 781, "top": 1019, "width": 34, "height": 34},
            "directional": True,
        },
        {
            "key": "r",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 828, "top": 1019, "width": 34, "height": 34},
            "directional": False,
        },
        {
            "key": "a",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 709, "top": 1063, "width": 34, "height": 34},
            "directional": True,
        },
        {
            "key": "s",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 756, "top": 1063, "width": 34, "height": 34},
            "directional": False,
        },
        {
            "key": "d",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 803, "top": 1063, "width": 34, "height": 34},
            "directional": False,
        },
        {
            "key": "f",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 849, "top": 1063, "width": 34, "height": 34},
            "directional": False,
        },
    ],
    "aeromancer": [
        {
            "key": "q",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 688, "top": 1019, "width": 34, "height": 34},
            "directional": False,
        },
        {
            "key": "w",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 737, "top": 1019, "width": 34, "height": 34},
            "directional": True,
        },
        {
            "key": "e",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": True,
            "castTime": 1,
            "doubleClick": False,
            "position": {"left": 781, "top": 1019, "width": 34, "height": 34},
            "directional": True,
        },
        {
            "key": "r",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 828, "top": 1019, "width": 34, "height": 34},
            "directional": False,
        },
        {
            "key": "a",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 709, "top": 1063, "width": 34, "height": 34},
            "directional": True,
        },
        {
            "key": "s",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 756, "top": 1063, "width": 34, "height": 34},
            "directional": False,
        },
        {
            "key": "d",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 803, "top": 1063, "width": 34, "height": 34},
            "directional": False,
        },
        {
            "key": "f",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 849, "top": 1063, "width": 34, "height": 34},
            "directional": False,
        },
    ],
    "blade": [
        {
            "key": "q",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": True,
            "position": {"left": 688, "top": 1019, "width": 34, "height": 34},
            "directional": False,
        },
        {
            "key": "w",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 737, "top": 1019, "width": 34, "height": 34},
            "directional": True,
        },
        {
            "key": "e",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 781, "top": 1019, "width": 34, "height": 34},
            "directional": True,
        },
        {
            "key": "r",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 828, "top": 1019, "width": 34, "height": 34},
            "directional": False,
        },
        {
            "key": "a",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 709, "top": 1063, "width": 34, "height": 34},
            "directional": True,
        },
        {
            "key": "s",
            "abilityType": "normal",
            "hold": True,
            "holdTime": 1,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 756, "top": 1063, "width": 34, "height": 34},
            "directional": False,
        },
        {
            "key": "d",
            "abilityType": "normal",
            "hold": True,
            "holdTime": 1,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 803, "top": 1063, "width": 34, "height": 34},
            "directional": False,
        },
        {
            "key": "f",
            "abilityType": "normal",
            "hold": True,
            "holdTime": 1,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 849, "top": 1063, "width": 34, "height": 34},
            "directional": False,
        },
    ],
    "reaper": [
        {
            "key": "q",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 688, "top": 1019, "width": 34, "height": 34},
            "directional": False,
        },
        {
            "key": "w",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 737, "top": 1019, "width": 34, "height": 34},
            "directional": True,
        },
        {
            "key": "e",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 781, "top": 1019, "width": 34, "height": 34},
            "directional": True,
        },
        {
            "key": "r",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 828, "top": 1019, "width": 34, "height": 34},
            "directional": False,
        },
        {
            "key": "a",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 709, "top": 1063, "width": 34, "height": 34},
            "directional": True,
        },
        {
            "key": "s",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 756, "top": 1063, "width": 34, "height": 34},
            "directional": False,
        },
        {
            "key": "d",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 803, "top": 1063, "width": 34, "height": 34},
            "directional": False,
        },
        {
            "key": "f",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 849, "top": 1063, "width": 34, "height": 34},
            "directional": False,
        },
    ],
    "souleater": [
        {
            "key": "q",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 688, "top": 1019, "width": 34, "height": 34},
            "directional": False,
        },
        {
            "key": "w",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 737, "top": 1019, "width": 34, "height": 34},
            "directional": True,
        },
        {
            "key": "e",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 781, "top": 1019, "width": 34, "height": 34},
            "directional": True,
        },
        {
            "key": "r",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 828, "top": 1019, "width": 34, "height": 34},
            "directional": False,
        },
        {
            "key": "a",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 709, "top": 1063, "width": 34, "height": 34},
            "directional": True,
        },
        {
            "key": "s",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 756, "top": 1063, "width": 34, "height": 34},
            "directional": False,
        },
        {
            "key": "d",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 803, "top": 1063, "width": 34, "height": 34},
            "directional": False,
        },
        {
            "key": "f",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "doubleClick": False,
            "position": {"left": 849, "top": 1063, "width": 34, "height": 34},
            "directional": False,
        },
    ],
}
